version: '3.6'
services:
  web:
    build: 
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - 
  wp-php:
    build: 
      context: ./wp-php
    volumes:
      - ./code:/code
