---
version: '3.7'
services:
  web:
    container_name: 'lunar_web'
    hostname: 'lunar_web'
    build:
      context: ./nginx
    expose:
      - 8080
    networks:
      - lunar-link
      - planet-link
    depends_on:
      - php
    restart: always
    volumes:
      - './www:/www'
      - './web/conf.yml:/home/h2o/h2o.conf'
      - './php-sock:/var/run'
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  php:
    container_name: 'lunar_php'
    hostname: 'lunar_php'
    build: 
      context: ./php
    expose: []
    networks:
      - lunar-link
    depends_on:
      - mysql
    restart: always
    volumes:
      - './www:/www'
      - './php-sock:/var/run'
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  mysql:
    container_name: 'lunar_mysql'
    hostname: 'lunar_mysql'
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'juvenile'
    volumes:
      - './mysql/data:/var/lib/mysql'
    networks:
      - lunar-link
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  mysql-exporter:
    container_name: 'lunar_mysql-exporter'
    hostname: 'lunar_mysql-exporter'
    image: prom/mysqld-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: 'root:juvenile@(mysql:3306)/'
    expose:
      - 9104
    networks:
      - lunar-link
      - planet-link
    depends_on:
      - mysql
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

networks:
  lunar-link:
    external: false
  planet-link:
    external: true

