version: '3.6'
services:
  web:
    container_name: "lunar_web"
    build: 
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wp-php
    restart: always
    volumes:
      - "/opt/books/certbot:/etc/letsencrypt"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/sites.d:/etc/nginx/sites.d"
      - "./nginx/auth:/etc/nginx/auth"
      - "./www:/www"
    networks:
      - wp-link
      - planet-link
    logging:
      driver: "json-file"
      options:
        max-file: '4'
        max-size: '250m'
  wp-php:
    container_name: "lunar_wp-php"
    build: 
      context: ./wp-php
    depends_on:
      - wp-mysql
    restart: always
    volumes:
      - "./www:/www"
    networks:
      - wp-link
    logging:
      driver: "json-file"
      options:
        max-file: '4'
        max-size: '250m'
  wp-mysql:
    container_name: "lunar_wp-mysql"
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "juvenile"
    volumes:
      - "./wp-mysql/db:/var/lib/mysql"
    networks:
      - wp-link
    logging:
      driver: "json-file"
      options:
        max-file: '4'
        max-size: '250m'
  wp-mysql-mon:
    container_name: "lunar_wp-mysql-mon"
    image: prom/mysqld-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "root:juvenile@(wp-mysql:3306)/"
    expose:
      - 9104
    networks:
      - wp-link
      - planet-link
    depends_on:
      - wp-mysql
    #command: []
     #- '--collect.info_schema.query_response_time'
     #- '--collect.info_schema.innodb_tablespaces'
     #- '--collect.info_schema.tables.databases'
     #- '--collect.perf_schema.tableiowaits'
     #- '--collect.perf_schema.indexiowaits'
     #- '--collect.perf_schema.tablelocks'
    logging:
      driver: "json-file"
      options:
        max-file: '4'
        max-size: '250m'

networks:
  wp-link:
    external: false
  planet-link:
    external: true
