---
version: '3.9'
services:
  web:
    container_name: 'lunar_web'
    hostname: 'lunar_web'
    image: 'lkwg82/h2o-http2-server:latest'
    expose:
      - 8080
    networks:
      - lunar-link
      - planet-link
    depends_on:
      - php
    restart: always
    command: 'h2o --conf /etc/h2o/conf.yml'
    volumes:
      - './www:/www'
      - './conf/h2o:/etc/h2o'
      - './run:/var/run'
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  php:
    container_name: 'lunar_php'
    hostname: 'lunar_php'
    build: 
      context: ./images/php
    expose: []
    networks:
      - lunar-link
    depends_on:
      - mysql
    restart: always
    volumes:
      - './www:/www'
      - './run:/var/run'
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

  mysql:
    container_name: 'lunar_mysql'
    hostname: 'lunar_mysql'
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - './var/mysql:/var/lib/mysql'
    networks:
      - lunar-link
    logging:
      driver: 'json-file'
      options:
        max-file: '4'
        max-size: '250m'

networks:
  default:
    driver: 'null'
  lunar-link:
    external: false
  planet-link:
    external: true

