version: '3.6'
services:
  web:
    container_name: "lunar_web"
    build: 
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wp-php
    restart: always
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/sites.d:/etc/nginx/sites.d"
      - "./nginx/auth:/etc/nginx/auth"
      - "./www:/www"
    networks:
      - wp-link
      - planet-link
  wp-php:
    container_name: "lunar_wp-php"
    build: 
      context: ./wp-php
    depends_on:
      - wp-mysql
    restart: always
    volumes:
      - "./www:/www"
    networks:
      - wp-link
  wp-mysql:
    container_name: "lunar_wp-mysql"
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "juvenile"
    volumes:
      - "./wp-mysql/db:/var/lib/mysql"
    networks:
      - wp-link
networks:
  wp-link:
    external: false
  planet-link:
    external: true
